log_level = "debug"
report_addr=""
projects = []
shell = "/bin/bash"
token = ""

timeout = 5

[micro]
region = "center"
org_id = "gophercron"
weight = 100
endpoint = "localhost:6306"

[mysql]
service="0.0.0.0:3306"
username=""
password=""
database=""
