log_level = "debug"
report_addr=""
projects = [] # 该agent需要执行的项目id
shell = "/bin/bash"
token = ""

timeout = 5

[micro]
region = "center"
org_id = "gophercron"
weight = 100
endpoint = "localhost:6306" # 中心服务的地址，域名也请带上端口号(HA等则仅需带上80 / 443端口号)

# report_addr 与 mysql 选一填写，mysql优先使用
[mysql]
service="0.0.0.0:3306"
username=""
password=""
database=""
