log_level = "debug"
report_addr=""
shell = "/bin/bash"

timeout = 5

[micro]
region = "center"
org_id = "gophercron"
weight = 100
endpoint = "localhost:6306" # 中心服务的地址，域名也请带上端口号(HA等则仅需带上80 / 443端口号)

# report_addr 与 mysql 选一填写，mysql优先使用
[mysql]
service="0.0.0.0:3306"
username=""
password=""
database=""  

[auth]
public_key = """
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDM82u8+ChkRwdpNxbzJypio0xb
+jdwWLd5DRcKL0cU8FlCD6fJH+YuMTMSf9RJaqQSIq0pKhyfHPHWnTSwLqudkzmG
tfKsupw9rpPkF25b9UOHL3h0KPdXaQgj866Dzc483JPcquRlJsrEOhfpY1vCt6Wq
0//vM79JBFBVoJ31mwIDAQAB
-----END PUBLIC KEY-----
"""

[[auth.projects]]
pid = 0 # project id
token = ""
