name: Build Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: ./script/build.sh
      - name: MakeRelease
        id: make_release
        run: ./script/makerelease.sh
      - name: LoadReleaseNote
        if: startsWith(github.ref, 'refs/tags/')
        run: cat ./release-note/${{ github.ref }}.md > Release.txt
      - name: Test
        if: startsWith(github.ref, 'refs/tags/')
        run: cat Release.txt
      - name: BuildRelease
        id: build_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: Release.txt
          files: gophercron-linux-amd64.tar.gz
